version: '3.3'

services:
  example-uast-viewer:
    build: ./examples/uast-viewer
    ports:
      - "8444:3000"
    depends_on:
      - grpcwebproxy

  # example-vanilla-bundled:
  #   build: ./examples/vanilla-bundled
  #   ports:
  #     - "8445:80"
  #   depends_on:
  #     - grpcwebproxy

  bblfsh:
    image: "bblfsh/bblfshd:v2.5.0"
    privileged: true
    volumes:
      - type: volume
        source: drivers
        target: /var/lib/bblfshd
    entrypoint: ["/bin/sh"]
    command:
    - "-c"
    - "bblfshd & sleep 5 && bblfshctl driver install --recommended && tail -f /dev/null"

  grpcwebproxy:
    image: mozgiii/docker-grpcwebproxy
    ports:
      - "8080:8080"
    depends_on:
      - bblfsh
    entrypoint: ["/grpcwebproxy"]
    command:
      - "--backend_addr=bblfsh:9432"
      - "--run_tls_server=false"

volumes:
  drivers:
